name: Generate Pac-Man

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: 786-soft/action-pacman-contribution-graph@v1.1.0
        with:
          github-user-name: tejaswini-keerthi
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-branch: pacman-output
